name: ohmygiraffe
base: core18
version: '1.1.0a'
summary: oh my giraffe
description: |
  a delightful game of survival

grade: stable
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

parts:
  ohmygiraffe:
    plugin: dump
    source: snap/local
    stage-packages:
      - love
      - freeglut3

apps:
  ohmygiraffe:
    extensions: [gnome-3-34]
    command: "usr/bin/love-0.9 $SNAP/oh-my-giraffe.love"
    plugs: [audio-playback, x11, opengl, unity7]
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP"
