name: ohmygiraffe
base: core18 # the base snap is the execution environment for this snap
version: '1.1.0a' # just for humans, typically '1.2+git' or '1.3.2'
summary: oh my giraffe
description: |
  a delightful game of survival

grade: stable
confinement: strict

parts:
  ohmygiraffe:
    plugin: dump
    source: snap/local
    stage-packages:
      - love
      - freeglut3

apps:
  ohmygiraffe:
    extensions: [gnome-3-34]
    command: "usr/bin/love-0.9 $SNAP/oh-my-giraffe.love"
    plugs: [audio-playback, x11, opengl, unity7]
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP"
